name: NuGet Release
# GitHub Actions cannot run the whole release procedure.
# Releases are initiated by running a script on developer machine, which then triggers this workflow via REST API.
on:
  repository_dispatch:
    types: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
    - name: Build
      run: dotnet pack --configuration Release
    - name: NuGet push
      run: dotnet nuget push */bin/Release/*.nupkg

